services:
  postgres:
    container_name: postgres-database
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database:/data/postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}

volumes:
  database: